class IndianCities {
  static const List<String> list = [
    "Aachyunthapuram, Andhra Pradesh",
    "Agra, Uttar Pradesh",
    "Ahmedabad, Gujarat",
    "Ajmer, Rajasthan",
    "Aligarh, Uttar Pradesh",
    "Ambala, Haryana",
    "Amravati, Maharashtra",
    "Amritsar, Punjab",
    "Asansol, West Bengal",
    "Aurangabad, Maharashtra",
    "Bangalore, Karnataka",
    "Bardhaman, West Bengal",
    "Bareilly, Uttar Pradesh",
    "Bathinda, Punjab",
    "Belgaum, Karnataka",
    "Berhampur, Odisha",
    "Bhagalpur, Bihar",
    "Bhilai, Chhattisgarh",
    "Bhopal, Madhya Pradesh",
    "Bhubaneswar, Odisha",
    "Bikaner, Rajasthan",
    "Bilaspur, Chhattisgarh",
    "Bokaro, Jharkhand",
    "Chandigarh, Chandigarh",
    "Chennai, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Cuttack, Odisha",
    "Dehradun, Uttarakhand",
    "Delhi NCR, Delhi",
    "Dhanbad, Jharkhand",
    "Dharamshala, Himachal Pradesh",
    "Dibrugarh, Assam",
    "Durgapur, West Bengal",
    "Faridabad, Haryana",
    "Gaya, Bihar",
    "Ghaziabad, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Guntur, Andhra Pradesh",
    "Gurugram, Haryana",
    "Guwahati, Assam",
    "Gwalior, Madhya Pradesh",
    "Haridwar, Uttarakhand",
    "Hubli, Karnataka",
    "Hyderabad, Telangana",
    "Indore, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Jaipur, Rajasthan",
    "Jalandhar, Punjab",
    "Jammu, Jammu and Kashmir",
    "Jamnagar, Gujarat",
    "Jamshedpur, Jharkhand",
    "Jodhpur, Rajasthan",
    "Kanpur, Uttar Pradesh",
    "Karimnagar, Telangana",
    "Kochi, Kerala",
    "Kolhapur, Maharashtra",
    "Kolkata, West Bengal",
    "Kollam, Kerala",
    "Kota, Rajasthan",
    "Kozhikode, Kerala",
    "Kurnool, Andhra Pradesh",
    "Lucknow, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Madurai, Tamil Nadu",
    "Mangalore, Karnataka",
    "Meerut, Uttar Pradesh",
    "Moradabad, Uttar Pradesh",
    "Mumbai, Maharashtra",
    "Mysore, Karnataka",
    "Muzaffarpur, Bihar",
    "Nagpur, Maharashtra",
    "Nashik, Maharashtra",
    "Nellore, Andhra Pradesh",
    "New Delhi, Delhi",
    "Nizamabad, Telangana",
    "Noida, Uttar Pradesh",
    "Panipat, Haryana",
    "Parsi, Maharashtra",
    "Patiala, Punjab",
    "Patna, Bihar",
    "Prayagraj, Uttar Pradesh",
    "Pune, Maharashtra",
    "Raipur, Chhattisgarh",
    "Rajkot, Gujarat",
    "Ranchi, Jharkhand",
    "Rohtak, Haryana",
    "Roorkee, Uttarakhand",
    "Rourkela, Odisha",
    "Saharanpur, Uttar Pradesh",
    "Salem, Tamil Nadu",
    "Shimla, Himachal Pradesh",
    "Silchar, Assam",
    "Siliguri, West Bengal",
    "Solapur, Maharashtra",
    "Srinagar, Jammu and Kashmir",
    "Surat, Gujarat",
    "Thiruvananthapuram, Kerala",
    "Thrissur, Kerala",
    "Tiruchirappalli, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Udaipur, Rajasthan",
    "Ujjain, Madhya Pradesh",
    "Vadodara, Gujarat",
    "Varanasi, Uttar Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Warangal, Telangana"
  ];
}
