// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXz-bYfx5OT3bR2xY-cGUBhAADous-bxQ',
    appId: '1:672092699296:web:6b4909e68d6495a83d67c5',
    messagingSenderId: '672092699296',
    projectId: 'zuno-application',
    authDomain: 'zuno-application.firebaseapp.com',
    storageBucket: 'zuno-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupd8plziRPE0TxTziJA1pATmTdxPjkz4',
    appId: '1:672092699296:android:163c3f1c3272c53e3d67c5',
    messagingSenderId: '672092699296',
    projectId: 'zuno-application',
    storageBucket: 'zuno-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lcFab5nZsRvILnMZTJuc-GKsv0MAAv0',
    appId: '1:672092699296:ios:0f9ee1d65eb1fee83d67c5',
    messagingSenderId: '672092699296',
    projectId: 'zuno-application',
    storageBucket: 'zuno-application.firebasestorage.app',
    iosBundleId: 'com.example.zunoApplication',
  );
}